Collapsible Map Menu
CDOT-CV/jpo-cvmanager pull request #113
Opened 2024-10-11 17:43 UTC by mwodahl

# PR Details
## Description

This PR adds a collapsible side menu to the Map component that includes map controls that were previously displayed over top of the map. 

## How Has This Been Tested?

This has been tested locally using docker.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ X ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ ] My changes require updates to the documentation:
  - [ ] I have updated the documentation accordingly.
- [ X ] My changes require updates and/or additions to the unit tests:
  - [ X ] I have modified/added tests to cover my changes.
- [ X ] All existing tests pass.

2024-10-24 18:17 UTC, jacob6838 commented
It's a little weird to me that the drawer displays over the entire UI, when it only affects the map. Would it not be better to have the drawer only display over the map?

2024-10-24 18:22 UTC, jacob6838 commented
I would advocate for more of a collapsible menu, rather than fully hidden/shown with a button. The MUI accordion works great for this style, or a sideways drawer. We use both of these in another MAP ui, and I like the way they look:
collapsed: 
![image](https://github.com/user-attachments/assets/ea07fce1-35db-4ab0-92ed-2b2001dbcc12)

expanded: 
![image](https://github.com/user-attachments/assets/d8b5d589-a4fc-42cf-be19-cdaf58b8777b)

2024-10-25 17:58 UTC, drewjj commented
I definitely agree with Jacob on his recommendations.

2024-12-12 21:59 UTC, drewjj commented
Is this ready for review again?

2024-12-12 22:10 UTC, mwodahl commented
> Is this ready for review again?

Yes

2024-12-16 21:39 UTC, jacob6838 requested changes
Overall I like the design. It's clean, and collapses out of the way. nicely. It would be convenient if it could persist the layer selections and accordion options on a refresh... but that is out of the scope of this task.

My only other thought is that the V2X Msg Viewer feels more like a map control than a layer... at least in the traditional sense, a layer would toggle data to show, not open another menu to show/filter data

2024-12-16 21:39 UTC, jacob6838 commented on webapp/src/pages/Map.tsx
> +                    borderBottom: menuSelection.includes('Display Message Counts') ? '1px solid black' : 'none',
When this gets merged with the MUI theming PR, we will want to pull these colors from the theme

2024-12-16 21:39 UTC, jacob6838 commented on webapp/src/pages/Map.tsx
> +                    backgroundColor: menuSelection.includes('Display Message Counts') ? '#1c1c1c' : '#3d3d3d',
The un-selected and hovered colors are way too similar, makes it really hard to tell whether a hovered option is selected

2024-12-16 21:39 UTC, jacob6838 commented on webapp/src/pages/Map.tsx
> +      setMenuSelection([...menuSelection, label])
The "Display Message Counts" and "Display RSU Status" options should override each other. The UI allows both to be selected, when only the most recently toggled one is active. They should toggle each other to make it more obvious which one is active

2024-12-23 17:11 UTC, payneBrandon commented
@mwodahl looks like a few merge conflicts

2025-01-03 21:17 UTC, mwodahl commented on webapp/src/pages/Map.tsx
> +                    borderBottom: menuSelection.includes('Display Message Counts') ? '1px solid black' : 'none',
Updated to pull colors from the theme

2025-01-03 21:18 UTC, mwodahl commented on webapp/src/pages/Map.tsx
> +                    backgroundColor: menuSelection.includes('Display Message Counts') ? '#1c1c1c' : '#3d3d3d',
Updated these to be more distinct

2025-01-03 21:18 UTC, mwodahl commented on webapp/src/pages/Map.tsx
> +      setMenuSelection([...menuSelection, label])
Updated these to override each other

2025-01-08 21:45 UTC, jacob6838 approved these changes
Changes look great!

2025-01-10 21:54 UTC, drewjj approved these changes

2025-01-13 21:30 UTC, payneBrandon approved these changes
lgtm!

2025-01-14 15:55 UTC, merged