Feature/configuration page
CDOT-CV/jpo-cvmanager pull request #115
Opened 2024-10-16 17:05 UTC by jacob6838

# PR Details

## Description

Adding the CIMMS Configuration page to the CVManager
- Migrating the Intersection Configuration API to use RTK Query
    - Creating intersectionApiSlice and adding to redux store
    - Using tags to automatically re-pull invalidated data
    - Using query refs to limit re-pulling of data
    - Using Selectors to cleanly reference data directly from api slice
- Migrating from [MUI v5 to v6](https://next.mui.com/x/migration/migration-pickers-v5/)
    - Re-factoring InputProps adornments to use slotProps
    - Re-factoring Grid components to new Grid2
    - Minor updates to DateTimePicker components
- Tweaking main MUI theme @mwodahl
    - Setting mode to 'dark' to improve text contrast
    - Removing previous color overrides (icons, typography, ...)
    - Manually overriding all Typography to use white text (Not sure why this is necessary, it should already be the case...)
- Minor Redux re-factoring
    - Implementing useAppSelector and useAppDispatch

**NOTE**
These changes are partially complete. There still needs to be a little more work ensuring that Organization-specific restrictions are put in place, and updated ConflictMonitor and ConflictVisualizer API images need to be pushed/referenced to enable these restrictions. As such, this is being created as a draft PR

## How Has This Been Tested?

These changes must be tested with the docker-compose-full-cm.yml compose file. You must ensure that your CM_SERVER_URL variable is set correctly to that the conflictvisualizer api can pull config params from the conflictmonitor

To test these changes, navigate to the IntersectionDashboard page, and click the Configuration tab. With intersection ID -1 selected, only defaults may be edited (far right action button). After selecting Intersection 12109, and selecting the Intersection filter tab, you can click the "+" button on the right to create a variable override for that intersection. After completing that dialog, there should be a "Overridden" chip in that row, and you should be able to edit or delete the override. You can also change to Intersection -1 to verify that it now only shows the default parameter for that intersection.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ ] My changes require updates to the documentation:
  - [ ] I have updated the documentation accordingly.
- [x] My changes require updates and/or additions to the unit tests:
  - [x] I have modified/added tests to cover my changes.
- [ ] All existing tests pass.

2024-12-12 22:03 UTC, drewjj commented
Is the entire conflict visualizer API intended to be included in this PR? I feel like the target should be the PR adding the cviz API to this repository.

Also, can we remove the files that only having formatting additions? This pull request is already massive and it is a bit of a headache to sift through all of the files with no meaningful changes.

2024-12-16 16:44 UTC, mwodahl reviewed
I had a few questions on logging statements otherwise this is looking really good!

2024-12-16 16:44 UTC, mwodahl commented on webapp/src/features/intersections/configuration/configuration-edit-form.tsx
> +  console.log('ConfigParamEditForm', parameter)
Is this necessary to keep in?

2024-12-16 16:44 UTC, mwodahl commented on webapp/src/features/intersections/configuration/configuration-list-table.tsx
> +  console.log(parameters)
Can this be removed?

2024-12-16 16:44 UTC, mwodahl commented on webapp/src/features/intersections/configuration/configuration-list-table.tsx
> +                  console.log('intersectionRow')
Same question here

2024-12-16 16:44 UTC, mwodahl commented on webapp/src/pages/Map.tsx
> +      console.log('WZDx openPopup', index, wzdxMarkers)
Do we need to keep log statements here?

2024-12-16 17:32 UTC, jacob6838 commented on webapp/src/features/intersections/configuration/configuration-edit-form.tsx
> +  console.log('ConfigParamEditForm', parameter)
removed

2024-12-16 17:32 UTC, jacob6838 commented on webapp/src/features/intersections/configuration/configuration-list-table.tsx
> +  console.log(parameters)
removed

2024-12-16 17:32 UTC, jacob6838 commented on webapp/src/features/intersections/configuration/configuration-list-table.tsx
> +                  console.log('intersectionRow')
removed

2024-12-16 17:32 UTC, jacob6838 commented on webapp/src/pages/Map.tsx
> +      console.log('WZDx openPopup', index, wzdxMarkers)
removed

2025-01-13 17:24 UTC, mwodahl approved these changes
This looks good to me - everything spun up correctly when run locally, the theming changes look good, and tests are passing.

2025-02-24 15:47 UTC, drewjj approved these changes
The configuration page looks good! Definitely took me a bit to get everything running locally but it seems like that is somewhat inevitable with so many moving parts required to get this part of it working.

2025-04-14 17:27 UTC, mcook42 commented
@jacob6838 Is there a UI mockup available for this configuration page?

2025-04-14 22:09 UTC, mcook42 requested changes
looks good overall. I had a question or two

2025-04-14 22:09 UTC, mcook42 commented on webapp/src/apis/intersections/mm-api.ts
> +    })
question(blocking): why do we need to make two calls to the same API where the only difference is one sets `latest=true` and the other omits `latest` ?

2025-04-14 22:09 UTC, mcook42 commented on webapp/src/features/intersections/map/control-panel.tsx
> +const formatMinutesAfterMidnightTime = (minutes) => {
suggestion(non-blocking): define the type for minutes
```suggestion
const formatMinutesAfterMidnightTime = (minutes: number) => {
```

2025-04-14 22:35 UTC, jacob6838 commented on webapp/src/apis/intersections/mm-api.ts
> +    })
I will add a clarifying comment to the code, but this is trying to pull the SPaT data within a time interval, accounting for data that is de-duplicated. De-deuplicated SPaT data will be sparse, potentially only emitting new messages once every minute when the light changes. This means that when we make a historical data query for a specific time interval, the first message might be far into the interval. To know that the state of the intersection was at the start of the window, we need the latest message before the interval, which is retrieved by the second query

2025-04-14 22:44 UTC, jacob6838 commented on webapp/src/apis/intersections/mm-api.ts
> +    })
Added a jsdoc comment describing this logic!

2025-04-14 22:47 UTC, mcook42 approved these changes

2025-04-15 19:17 UTC, merged