Architecture and Dataflow Flowchart
CDOT-CV/jpo-cvmanager pull request #124
Opened 2024-11-05 18:31 UTC by drewjj

# PR Details

## Description

This pull request includes a flowchart to help explain the complexities of the CV Manager and how it communicates throughout all of its microservices and databases.

The diagram was made using draw.io and the readme was updated to include the diagram.

## How Has This Been Tested?

N/A

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [x] My changes require updates to the documentation:
  - [x] I have updated the documentation accordingly.
- [ ] My changes require updates and/or additions to the unit tests:
  - [ ] I have modified/added tests to cover my changes.
- [x] All existing tests pass.

2024-11-05 18:50 UTC, dmccoystephenson approved these changes
Looks great to me, this is awesome!

2024-11-05 19:05 UTC, jacob6838 approved these changes
A few small comments:
1. The Conflict Visualizer API reads from Kafka (live intersection data)
2. Technically, the webapp and both APIs talk directly with Keycloak. If this adds too much clutter I guess its ok
3. Arrow directions
    - The cvmanager API -> postgres arrow should be bi-directional
    - The Conflict Visualizer API -> MongoDB arrow should be bi-directional
    - The Conflict Visualizer API -> PostgreSQL arrow should be reversed (from postgres to API)

2024-11-05 19:22 UTC, John-Wiens commented on docs/CVManagerArchFlowchart.png
The Conflict Visualizer API is currently able to directly talk to keycloak. This allows it to validate tokens against keycloak and to create new users in keycloak. Additionally, the conflict visualizer API connects to Kafka so that it can get recieve real time SPaT / MAP / BSM message updates for the live viewer

2024-11-05 19:26 UTC, John-Wiens commented
I believe that RSU units receive BSMs from OBU units.  I think we need an arrow from the OBU units to the RSU units. We could also consider an arrow from the OBU units back to itself because OBUs can communicate directly with one another via BSMs.

2024-11-05 20:03 UTC, Michael7371 requested changes

2024-11-05 20:03 UTC, Michael7371 commented on docs/CVManagerArchFlowchart.png
The OBU OTA server also communicates with Postgres to log all requested firmware files and the status (success/fail) of the request.

2024-11-05 20:21 UTC, drewjj commented
> A few small comments:
> 
> 1. The Conflict Visualizer API reads from Kafka (live intersection data)
> 2. Technically, the webapp and both APIs talk directly with Keycloak. If this adds too much clutter I guess its ok
> 3. Arrow directions
>    
>    * The cvmanager API -> postgres arrow should be bi-directional
>    * The Conflict Visualizer API -> MongoDB arrow should be bi-directional
>    * The Conflict Visualizer API -> PostgreSQL arrow should be reversed (from postgres to API)

I wrote the arrows from the perspective of the origin of the request. Not sure how PosgreSQL would cause the API to do something unless it was periodici

2024-11-05 20:49 UTC, jacob6838 commented
> > A few small comments:
> > 
> > 1. The Conflict Visualizer API reads from Kafka (live intersection data)
> > 2. Technically, the webapp and both APIs talk directly with Keycloak. If this adds too much clutter I guess its ok
> > 3. Arrow directions
> >    
> >    * The cvmanager API -> postgres arrow should be bi-directional
> >    * The Conflict Visualizer API -> MongoDB arrow should be bi-directional
> >    * The Conflict Visualizer API -> PostgreSQL arrow should be reversed (from postgres to API)
> 
> I wrote the arrows from the perspective of the origin of the request. Not sure how PosgreSQL would cause the API to do something unless it was periodici

ah ok, I was thinking of which way the information flowed

2024-11-05 21:20 UTC, drewjj commented
> I believe that RSU units receive BSMs from OBU units. I think we need an arrow from the OBU units to the RSU units. We could also consider an arrow from the OBU units back to itself because OBUs can communicate directly with one another via BSMs.

In my opinion, this is borderline out of scope since it is more of an edge architecture detail. I could see it being justifiable since it will explain the origin of the BSM message if someone was trying to trace the dataflow beyond the edge RSU forwarding them. I will add a line between the OBU and RSU.

2024-11-05 21:23 UTC, drewjj commented
I am going to adjust this diagram to follow the dataflow as the name suggests to prevent confusion.

2024-11-06 21:07 UTC, John-Wiens approved these changes

2024-11-06 21:07 UTC, Michael7371 approved these changes
LGTM!

2024-11-06 21:33 UTC, jacob6838 approved these changes
Changes look great!

2024-11-06 21:44 UTC, merged