GeoSpatial Configuration Updates
CDOT-CV/jpo-cvmanager pull request #4
Opened 2023-05-05 21:02 UTC by Michael7371

Updates to support geospatially updating RSU SNMP forwarding.

For testing feel free to use the updated API that is already deployed in cloud run by adding the sub-string "config---" between "https://" and "rsu-manager" in the REACT_APP_GATEWAY_BASE_URL_DEV environmental variable.

2023-05-09 06:47 UTC, drewjj commented
![image](https://user-images.githubusercontent.com/31270488/237016249-9449e0d7-177e-4c0a-ab4e-8cdedaf5900c.png)
Maybe we would want to automatically close the multi-select if we select another single RSU.

2023-05-09 06:49 UTC, drewjj commented
Why did we add RSU indexes back into the SNMP configuration? This was originally abstracted to be automatically handled by the API since this concept is not something we want the user of the CV Manager to need to understand.

2023-05-09 07:01 UTC, drewjj commented
![image](https://user-images.githubusercontent.com/31270488/237017269-040228ea-4b0a-4778-9df6-e0a400a0609c.png)
I don't mind this menu but I feel like the UX choices are a little convoluted. I wonder if this can be streamlined to be more intuitive. Maybe hide the X until there is something to clear out on the map and hide it again when it is cleared. 

If you turn the toggle on, add some points to create a complete polygon, and then turn it off before clicking the "CONFIGURE RSU'S" you will get it in some sort of soft lock where it no longer works until you clear it. Maybe finding a way to consolidate the menu here into less independent buttons and more of a stateful menu which helps guide the user through the correct manner of using the UX would be nice.

Also, I feel like we should change the text to "Configure RSUs" without the apostrophe and only capitalizing the first letter of each word.  All of the other buttons use lowercase letters so this button is pretty unique which kinda contradicts our CSS choices at the moment. We could always redesign our CSS to be different but I think that can be saved for a different pull request.

2023-05-09 07:03 UTC, drewjj requested changes
My requests are reflected in my comments. They are more UX related so I made them comments to add pictures. I am happy to help provide some ideas with the UX stuff if you want to reach out to me!

2023-05-09 09:27 UTC, Michael7371 commented
> ![image](https://user-images.githubusercontent.com/31270488/237016249-9449e0d7-177e-4c0a-ab4e-8cdedaf5900c.png)
> Maybe we would want to automatically close the multi-select if we select another single RSU.

Yeah I like that idea.

2023-05-09 09:28 UTC, Michael7371 commented
> Why did we add RSU indexes back into the SNMP configuration menus? This was originally abstracted to be automatically handled by the API since this concept is not something we want the user of the CV Manager to need to understand.

I thought it was needed for the deletion endpoint, if it isn't then we can get rid of it.

2023-05-09 14:32 UTC, drewjj commented
> > Why did we add RSU indexes back into the SNMP configuration menus? This was originally abstracted to be automatically handled by the API since this concept is not something we want the user of the CV Manager to need to understand.
> 
> I thought it was needed for the deletion endpoint, if it isn't then we can get rid of it.

I do not believe it is required. The API's current deletion logic should loop through the RSUs, perform basic snmpwalks on all of them and identify the index that matches the specified message type and destination IP and then delete that index.

2023-05-09 15:28 UTC, Michael7371 commented
> > > Why did we add RSU indexes back into the SNMP configuration menus? This was originally abstracted to be automatically handled by the API since this concept is not something we want the user of the CV Manager to need to understand.
> > 
> > 
> > I thought it was needed for the deletion endpoint, if it isn't then we can get rid of it.
> 
> I do not believe it is required. The API's current deletion logic should loop through the RSUs, perform basic snmpwalks on all of them and identify the index that matches the specified message type and destination IP and then delete that index.

Awesome! I will get that updated

2023-05-09 15:52 UTC, Michael7371 commented
@drewjj I just pushed a commit that addresses most of your comments. Also, you were right about the index not being required, I didn't see that the rsu_commands.py has the functionality of getting the message index. I was able to hide the clear button when it isn't useful, as well as changed the text format to not be in all caps. The configure menu was also updated to hide the multi-rsu selection if a single rsu is selected. I also added a clear button for the single rsu config menu to keep the menu view consistent.

2023-05-18 18:34 UTC, drewjj approved these changes
Awesome, it behaves nicely and works well. Great job!

2023-06-14 20:45 UTC, drewjj approved these changes
Re-approving to show I have tested the current state of the pull request since my old approval is stale.

2023-06-23 19:01 UTC, payneBrandon approved these changes
Looking good! A couple clarifying questions is all

2023-06-23 19:01 UTC, payneBrandon commented on api/.gitignore
> +env
Should this be ".env"?

2023-06-23 19:01 UTC, payneBrandon commented on webapp/src/components/SnmpwalkMenu.js
> +                      className="deletbutton"
Is this the correct class name?

2023-06-23 19:19 UTC, Michael7371 commented on api/.gitignore
> +env
I added it because I was using a virtual environment. I'll add .env as well.

2023-06-23 21:06 UTC, payneBrandon commented on webapp/src/components/SnmpwalkMenu.js
> +                      className="deletbutton"
Looks like it reference the right css class, just misspelled in both locations. We can address this later, closing.

2023-06-23 21:07 UTC, merged