Adding Message Counts and RSU Ping Images to Repository
CDOT-CV/jpo-cvmanager pull request #6
Opened 2023-05-22 18:22 UTC by Michael7371

Addition of the add-ons to the cvmanager for retrieving RSU status ping times as well as message counts for CV2x message types. Added support for a local deployment with MongoDB and a local PostgreSQL in addition to the original BigQuery implementation.

2023-06-16 22:01 UTC, dmccoystephenson approved these changes
The code looks good and the tests all pass!

2023-06-21 21:04 UTC, payneBrandon requested changes
Looking good, just a couple questions

2023-06-21 21:04 UTC, payneBrandon commented on addons/images/bsm_query/sample.env
> +# Name of output geospatial collection
```suggestion
# Name of output geospatial MongoDB collection

```
Let's quantify this is for a MongoDB collection...my first though was a JSON document or something which is clearly wrong after looking at things but it made me pause.

2023-06-21 21:04 UTC, payneBrandon commented on addons/images/count_metric/README.md
> +The docker image can be deployed in K8S using the helm deployment. Make sure to create the service account using the Terraform deployment before creating the image using helm.
Since we talk about deploying in K8s should we include a manifest alongside the existing `docker-compose.yml` file? That might help clarify the credentials being uploaded via Secret as well as give an example of actual deployment.

2023-06-21 21:04 UTC, payneBrandon commented on addons/images/count_metric/README.md
> +Custom metrics do not need to be created first but for testing purposes they can be. The provided Python script [metriccreation.py](metriccreation.py) contains two Python functions that will help wit
Missing `metriccreation.py` here.

2023-06-21 21:04 UTC, payneBrandon commented on addons/images/count_metric/README.md
> +<b>RSU_INFO_ENDPOINT:</b> The HTTP endpoint to a GCP Cloud Function or some other endpoint that returns a JSON list of GeoLocation JSON.
Looks like we're missing the MONGO_DB_XX environment variables and associated documentation.

2023-06-21 21:04 UTC, payneBrandon commented on addons/images/rsu_ping_fetch/README.md
> +- [Usage](#usage)
```suggestion

```

2023-06-21 21:04 UTC, payneBrandon commented on addons/images/rsu_ping_fetch/README.md
> +This directory describes an image that runs within the RSU Manager GKE Cluster. It is used to populate the PostGreSQL database with data from the Zabbix instance monitoring RSU status. It expects the
Let's update this to be a bit higher-level to apply to anyone who may pull this repo in the future. We'll want to call out that this solution relies on a Zabbix server in place to monitor uptime for a set of RSUs and this script is designed to scrape the exposed Zabbix endpoints to pull that data into the CV Manager application ecosystem to avoid strain on Zabbix.

2023-06-21 21:04 UTC, payneBrandon commented on addons/images/bsm_query/bsm_query.py
> +import json
Unused, remove?

2023-06-21 22:29 UTC, drewjj commented on addons/images/rsu_ping_fetch/README.md
> +- [Usage](#usage)
Addressed

2023-06-21 22:30 UTC, drewjj commented on addons/images/rsu_ping_fetch/README.md
> +This directory describes an image that runs within the RSU Manager GKE Cluster. It is used to populate the PostGreSQL database with data from the Zabbix instance monitoring RSU status. It expects the
Addressed

2023-06-22 15:35 UTC, Michael7371 commented on addons/images/count_metric/README.md
> +The docker image can be deployed in K8S using the helm deployment. Make sure to create the service account using the Terraform deployment before creating the image using helm.
I was talking with drew, and I think we are going to hold off on adding the k8 support until we have the templates ready for all the addons to be deployed. So I am just going to remove the k8 information from this readme for now.

2023-06-22 15:36 UTC, Michael7371 commented on addons/images/count_metric/README.md
> +Custom metrics do not need to be created first but for testing purposes they can be. The provided Python script [metriccreation.py](metriccreation.py) contains two Python functions that will help wit
No longer needed, I will remove this from the readme.

2023-06-23 21:04 UTC, payneBrandon approved these changes
Looks good to me!

2023-06-23 21:05 UTC, merged