PSM Visualization
CDOT-CV/jpo-cvmanager pull request #60
Opened 2024-04-08 22:43 UTC by Michael7371

# PR Details

## Description

This PR includes the following changes:

1. Removed bsm_query addon in favor of a generic geo_msg_query service that can take in a list of msg types
2. Reworked the CV manager API to handle querying for different msg types
3. Reworked the CV manager webapp to support selecting message type before executing queries
4. Fixed the BSM query logic to auto pull in dates on the selector rather than making the user set it initially. The default is to query for a day of data.
5. Reworked the docker_compose_addons.yml to pull env variables from the root .env file rather than using remote .env files
6. Changed the mongo_db_uri variable to mongo_conn_uri name to fix issues with pulling in url arguments for the mongo connection uri information.

## How Has This Been Tested?

This has been testing by using unit tests for all code refactors, as well as setting up the ODE to spin up a RBAC and Replica Set Mongo deployment to use for the geo_msg_query add-on. I then ran the udpsender_bsm and udpsender_psm test python script in the ODE repository and then verified the CV manager can see these messages on the UI.

## Types of changes

- [ x ] Defect fix (non-breaking change that fixes an issue)
- [ x ] New feature (non-breaking change that adds functionality)
- [ x ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ x ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ x ] My changes require updates to the documentation:
  - [ x ] I have updated the documentation accordingly.
- [ x ] My changes require updates and/or additions to the unit tests:
  - [ x ] I have modified/added tests to cover my changes.
- [ x ] All existing tests pass.

2024-05-08 22:06 UTC, drewjj commented
Looks like tests aren't passing based off the automated checks

2024-05-09 22:12 UTC, drewjj approved these changes
Alright, looks good now! Really nice changes to the interface behavior too

2024-05-10 14:24 UTC, mwodahl reviewed
Just had a couple of quick questions - overall looks really good and runs well!

2024-05-10 14:24 UTC, mwodahl commented on webapp/sample.env.local
> +REACT_APP_VIEWER_MESSAGE_TYPES='BSM'
Should this include PSM as well?

2024-05-10 14:24 UTC, mwodahl commented on webapp/src/pages/Map.tsx
> +                  // maxDateTime={dayjs(endGeoMsgDate === '' ? new Date() : endGeoMsgDate)}
Should these be removed?

2024-05-10 20:22 UTC, Michael7371 commented on webapp/sample.env.local
> +REACT_APP_VIEWER_MESSAGE_TYPES='BSM'
Sure, ill add it.

2024-05-10 20:22 UTC, Michael7371 commented on webapp/src/pages/Map.tsx
> +                  // maxDateTime={dayjs(endGeoMsgDate === '' ? new Date() : endGeoMsgDate)}
Yep, good catch.

2024-05-10 21:01 UTC, payneBrandon requested changes
Just a couple questions, looking good!

2024-05-10 21:01 UTC, payneBrandon commented on services/addons/images/geo_msg_query/geo_msg_query.py
> +    set_indexes(db, MONGO_GEO_OUTPUT_COLLECTION, MONGO_TTL)
How often is this called? Do we need to update our indexes every time?

2024-05-10 21:01 UTC, payneBrandon commented on webapp/sample.env.local
> +REACT_APP_COUNT_MESSAGE_TYPES='BSM,SSM,SPAT,SRM,MAP'
Are we not counting PSM as well?

2024-05-10 21:01 UTC, payneBrandon commented on webapp/src/apis/rsu-api-types.ts
> +// export type MsgDataPostBody = {
Clean out?

2024-05-10 21:03 UTC, Michael7371 commented on services/addons/images/geo_msg_query/geo_msg_query.py
> +    set_indexes(db, MONGO_GEO_OUTPUT_COLLECTION, MONGO_TTL)
On boot up of the container. I have it such that it will only update the indexes if the environmental variables have changed (ie: TTL duration).

2024-05-10 21:16 UTC, Michael7371 commented on webapp/sample.env.local
> +REACT_APP_COUNT_MESSAGE_TYPES='BSM,SSM,SPAT,SRM,MAP'
I just set the defaults to the dataset that CDOT has. I was thinking we would wait to display PSM counts until they had data coming in.

2024-05-10 21:18 UTC, Michael7371 commented on webapp/sample.env.local
> +REACT_APP_COUNT_MESSAGE_TYPES='BSM,SSM,SPAT,SRM,MAP'
Ill add it to the sample.env so then people know that it can be set.

2024-05-10 21:25 UTC, payneBrandon approved these changes
lgtm!

2024-05-10 21:26 UTC, merged