Organization dropdown bug fix
CDOT-CV/jpo-cvmanager pull request #80
Opened 2024-06-25 16:06 UTC by mwodahl

# PR Details
## Description

This PR modifies the organization dropdown menu to update correctly after a user-organization assignment is created, deleted, or edited for the current user. Additionally, the tabs displayed now update correctly after a new organization is selected from the dropdown menu. 

## How Has This Been Tested?

This has been tested locally via docker-compose with user-organization add, edit, and delete. Additionally, organization delete has been tested and the tabs shown to the user have been verified to update correctly after switching organizations.

## Types of changes

- [ x ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ ] My changes require updates to the documentation:
  - [ ] I have updated the documentation accordingly.
- [ x ] My changes require updates and/or additions to the unit tests:
  - [ x ] I have modified/added tests to cover my changes.
- [ x ] All existing tests pass.

2024-06-25 20:11 UTC, dmccoystephenson requested changes

2024-06-25 20:11 UTC, dmccoystephenson commented on webapp/src/features/adminOrganizationTab/AdminOrganizationTab.tsx
> +        defaultOrgData = null
A comment explaining why the defaultOrgData variable is being set to null here and what effect that has would be helpful.

2024-06-28 03:03 UTC, drewjj approved these changes
This is actually really nice. Everything seems to work well when switching between orgs with enforcing role switches. The dropdown definitely gets updated properly with the adding or removal of an org. 

Looks like the one thing that is a little janky is the RSU map doesn't refresh properly. Not sure if this was intended to be just the dropdown or if it intended to get the org switching working entirely.

2024-07-02 14:20 UTC, mwodahl commented on webapp/src/features/adminOrganizationTab/AdminOrganizationTab.tsx
> +        defaultOrgData = null
Added a comment to explain this useEffect logic.

2024-07-05 13:09 UTC, dmccoystephenson commented on webapp/src/features/adminOrganizationTab/AdminOrganizationTab.tsx
> +        defaultOrgData = null
Awesome!

2024-07-05 13:11 UTC, dmccoystephenson approved these changes
Looks good to me!

2024-07-18 05:57 UTC, merged