Add toast notifications
CDOT-CV/jpo-cvmanager pull request #82
Opened 2024-06-25 16:19 UTC by mwodahl

# PR Details
## Description

This PR adds toast notifications to the admin menus, the contact support menu, and the snmp menus. Additionally, some of the success/error state logic has been removed as it is no longer needed with the toast notifications. 

## How Has This Been Tested?

This was tested locally via docker-compose and was verified to work with the admin add/edit/delete menus, the contact support menu, and the snmp menus. 

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ X ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ ] My changes require updates to the documentation:
  - [ ] I have updated the documentation accordingly.
- [ x ] My changes require updates and/or additions to the unit tests:
  - [ x ] I have modified/added tests to cover my changes.
- [ x ] All existing tests pass.

2024-06-28 03:47 UTC, drewjj commented
The toast notifications look really nice. It looks like they may not be entirely accurate in some cases. A good example is when trying to delete a SNMP config when it is running locally. The API fails to really delete it but the toast notification says it was successful. Not sure if the API is just not returning a good failure case but just wanted to point this out.

![image](https://github.com/CDOT-CV/jpo-cvmanager/assets/31270488/eb12bf3a-7588-4b98-8aca-8de8bde864b7)

2024-06-28 03:49 UTC, drewjj commented
I am getting this error message when I try to delete a RSU on the admin page.

Cannot read properties of undefined (reading 'success')
TypeError: Cannot read properties of undefined (reading 'success')
    at http://localhost:3000/static/js/bundle.js:10101:20

2024-06-28 03:50 UTC, drewjj commented
The users adding/deleting works great.

2024-07-03 16:28 UTC, mwodahl commented
> I am getting this error message when I try to delete a RSU on the admin page. However the API does delete it. Seems to be a web app handling issue.
> 
> Cannot read properties of undefined (reading 'success') TypeError: Cannot read properties of undefined (reading 'success') at http://localhost:3000/static/js/bundle.js:10101:20

I was able to replicate this and it looks like the API was failing to delete an RSU as there were still records tied to it in the public.snmp_msgfwd_config table. This was also occurring in dev so I updated the API to delete those records and now this error should no longer be present.

2024-07-03 16:35 UTC, mwodahl commented
> The toast notifications look really nice. It looks like they may not be entirely accurate in some cases. A good example is when trying to delete a SNMP config when it is running locally. The API fails to really delete it but the toast notification says it was successful. Not sure if the API is just not returning a good failure case but just wanted to point this out.
> 
> ![image](https://private-user-images.githubusercontent.com/31270488/344021815-eb12bf3a-7588-4b98-8aca-8de8bde864b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjQzNDksIm5iZiI6MTcyMDAyNDA0OSwicGF0aCI6Ii8zMTI3MDQ4OC8zNDQwMjE4MTUtZWIxMmJmM2EtNzU4OC00Yjk4LThhY2EtOGRlOGJkZTg2NGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE2MjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMmI0NzI5NjcyZDdkYTU2MDBhMTQ5ODFmNDdhZjBlNWM5MjZlYzAzYzlkODY2ODk1NzkzNDBmYzkzMDY4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lizrFVX0zcL-NfmaLsedNzUcGrhJjBcBMBPXAyxmJOk)

It looks like the API is currently returning a 200 code regardless of the SNMP command status which is why this is showing a successful delete. Would it interfere with anything to refactor the API to return a different code when it fails to perform an SNMP command?

2024-07-11 19:44 UTC, dmccoystephenson requested changes
I am running into failures when executing the webapp unit tests:

![image](https://github.com/CDOT-CV/jpo-cvmanager/assets/21204351/7562c629-8a56-48c7-b004-b6ada908c44b)

Looks like the snapshots need to be updated

2024-07-11 19:44 UTC, dmccoystephenson commented on webapp/src/features/adminEditUser/adminEditUserSlice.tsx
> +      return { submitAttempt: true, success: false, message: 'Please fill out all required fields' }
What is the purpose of this `submitAttempt` variable? Does it refer to whether the user has attempted to submit the form? Renaming the variable to be more descriptive may be helpful here.

2024-07-18 19:51 UTC, drewjj approved these changes
I think we can move forward with this how it is. If the SNMP always gives a 200 that is fine for now I suppose. We may want to consider changing that in the future to prevent confusion.

2024-07-19 15:38 UTC, merged