Adding Snmp Version to RSU data
CDOT-CV/jpo-cvmanager pull request #9
Opened 2023-06-26 14:33 UTC by jacob6838

Adding SNMP version to rsu sql tables, rsu adding/creation/retrieval queries, and creation/editing pages

2023-06-30 21:11 UTC, payneBrandon requested changes
I'm not able to see the new changes coming across - targeting localhost, I end up with cors errors and targeting the dev deployed service doesn't seem to have the changes needed for this PR. Am I missing something?

2023-06-30 21:11 UTC, payneBrandon commented on documents/sql_scripts/CVManager_SampleData.sql
> +	username, password, nickname)
Copy/pasta? Probably should be version_code and nickname that we're inserting here.

2023-06-30 21:11 UTC, payneBrandon commented on documents/sql_scripts/CVManager_SampleData.sql
> +INSERT INTO public.snmp_versions(
Not sure we need to include it here since this is the public repo, but did we update our existing RSUs include the new snmp_version column and default our units to a spec?

2023-06-30 21:11 UTC, payneBrandon commented on api/src/rsu_commands.py
> +          "LEFT JOIN public.snmp_versions AS snmp ON snmp.snmp_version_id = rd.snmp_version_id " \
Do we need to add this to our select list somehow? If we don't need the snmp_versions for this query we can leave out the join.

2023-07-03 14:45 UTC, jacob6838 commented on documents/sql_scripts/CVManager_SampleData.sql
> +	username, password, nickname)
Updated

2023-07-03 14:46 UTC, jacob6838 commented on documents/sql_scripts/CVManager_SampleData.sql
> +INSERT INTO public.snmp_versions(
We have not added this to the existing RSUs. I will talk with Drew about the best way to do this

2023-07-03 14:46 UTC, jacob6838 commented on api/src/rsu_commands.py
> +          "LEFT JOIN public.snmp_versions AS snmp ON snmp.snmp_version_id = rd.snmp_version_id " \
Good point, the snmp_version is not useful here. I removed this

2023-07-06 12:53 UTC, jacob6838 commented
Deployment plan:
1. Alter table with addition of new field
2. Add SNMP version "4.1" to all current RSUs

2023-07-06 12:55 UTC, jacob6838 commented
To run this locally, you have to do a few things:
1. Set DB_HOST in root .env file (set to YOUR_HOST_IP:5432)
2. Add DB_HOST to the environment section of the api in docker-compose.yml
3. Change the inbound port of the webapp in docker-compose.yml to 3000 or 3001
4.

2023-07-06 12:56 UTC, jacob6838 commented on documents/sql_scripts/CVManager_SampleData.sql
> +INSERT INTO public.snmp_versions(
See the deployment plan below

2023-07-17 13:44 UTC, jacob6838 commented
I just added the script for updating the previous tables to include the SNMP version

2023-07-17 20:53 UTC, jacob6838 commented
The API has been deployed to Dev: https://snmpversion---rsu-manager-cloud-run-api-kcrcl2kkaq-uc.a.run.app
The database was updated to add the snmp_version table and fields

2023-07-19 23:45 UTC, drewjj approved these changes
Tests all pass, everything looks good here. Tracking this makes a lot of sense. It might make sense to rework how we handle generating our SNMP commands based on this detail in the database instead of relying on the vendor to be the determining factor. Something to consider in the future I suppose.

2023-07-20 19:38 UTC, payneBrandon approved these changes
Just the one comment, looks good!

2023-07-20 19:38 UTC, payneBrandon commented on api/src/middleware.py
> +import time
Doesn't seem to be used, can we remove?

2023-07-20 20:39 UTC, jacob6838 commented on api/src/middleware.py
> +import time
fixed!

2023-07-20 21:21 UTC, payneBrandon approved these changes

2023-07-20 21:22 UTC, merged